import './style.css';

const defaults=[{name:'Finder',icon:'📁',type:'finder',pinned:true},{name:'App Store',icon:'🛍️',type:'store',pinned:true},{name:'Settings',icon:'⚙️',type:'settings',pinned:true},{name:'About Dev Credits',icon:'👨‍💻',type:'about',pinned:true},{name:'lcc-math',url:'https://lcc-math.pages.dev',icon:'🧮',type:'web',pinned:true},{name:'Browser',url:'https://example.com',icon:'🌐',type:'web',pinned:true}];
let apps=JSON.parse(localStorage.getItem('tuff.apps')||'null')||defaults,windows=[],active=null,proxyPrefix=localStorage.getItem('tuff.proxyPrefix')||'/scramjet/embed.html?url=';
const root=document.getElementById('app');
const save=()=>localStorage.setItem('tuff.apps',JSON.stringify(apps));
const saveProxy=()=>localStorage.setItem('tuff.proxyPrefix',proxyPrefix);
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function icon(a){return a.icon||'🌐'}
function frameUrl(url){return `${proxyPrefix}${encodeURIComponent(url)}`}
function openApp(app){active=app.name;if(!windows.some(w=>w.name===app.name))windows.push(app);render()}
function closeApp(name){windows=windows.filter(w=>w.name!==name);if(active===name)active=windows.at(-1)?.name||null;render()}
function togglePin(name){apps=apps.map(a=>a.name===name?{...a,pinned:!a.pinned}:a);save();render()}
function addCustom(){const name=document.getElementById('custom-name').value.trim(),raw=document.getElementById('custom-url').value.trim(),ic=document.getElementById('custom-icon').value.trim();if(!name||!raw)return;apps.push({name,url:/^https?:\/\//.test(raw)?raw:`https://${raw}`,icon:ic||'🌐',type:'web',pinned:apps.filter(a=>a.pinned).length<12});save();render()}
function appButton(a){return `<button data-open="${esc(a.name)}"><span>${esc(icon(a))}</span>${esc(a.name)}</button>`}
function content(win){if(win.type==='finder')return `<div class="finder"><h2>Start Menu</h2><p>Finder is the start menu where every installed and custom app appears.</p><div class="appgrid">${apps.map(appButton).join('')}</div></div>`;if(win.type==='store')return `<div class="store"><h2>App Store</h2><p>App list format: <code>url="lcc-math.pages.dev" icon="yuriconurlhere" name="lcc-math"</code>.</p><div class="list">${apps.map(a=>`<div><span>${esc(icon(a))}</span><b>${esc(a.name)}</b><small>${esc(a.url||a.type)}</small><button data-open="${esc(a.name)}">Open</button></div>`).join('')}</div><h3>Add custom app</h3><div class="custom"><input id="custom-name" placeholder="name"><input id="custom-url" placeholder="url"><input id="custom-icon" placeholder="icon optional"><button id="add-custom">＋ Add</button></div></div>`;if(win.type==='settings')return `<div class="settings"><h2>Proxy Settings</h2><label>Static Scramjet embed path<input id="proxy" value="${esc(proxyPrefix)}"></label><h3>Dock pins (max 12)</h3>${apps.map(a=>`<button class="pinrow" data-pin="${esc(a.name)}">${a.pinned?'📌':'○'} ${esc(a.name)}<span>${a.pinned?'Unpin':'Pin'}</span></button>`).join('')}</div>`;if(win.type==='about')return `<div class="about"><h2>About Dev Credits</h2><p>Cloned and customized from macos-web, with static Scramjet embed support from staticsjv2.</p><p>Powered by Vercel branding was removed for this Tuff desktop build.</p></div>`;return `<iframe title="${esc(win.name)}" src="${esc(frameUrl(win.url))}"></iframe>`}
function render(){const dock=apps.filter(a=>a.pinned).slice(0,12);root.innerHTML=`<main class="desktop"><section class="menubar"><span>Finder</span><span>File</span><span>Edit</span><span>View</span><span class="right">${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></section>${windows.map(w=>`<article class="window ${active===w.name?'active':''}"><header><button data-close="${esc(w.name)}">×</button><strong>${esc(w.name)}</strong></header><div class="content">${content(w)}</div></article>`).join('')}<nav class="dock">${dock.map(a=>`<button title="${esc(a.name)}" data-open="${esc(a.name)}">${/^https?:\/\//.test(icon(a))?`<img src="${esc(icon(a))}" alt="">`:`<span>${esc(icon(a))}</span>`}</button>`).join('')}</nav></main>`}
root.addEventListener('click',e=>{const open=e.target.closest('[data-open]'),close=e.target.closest('[data-close]'),pin=e.target.closest('[data-pin]');if(open)openApp(apps.find(a=>a.name===open.dataset.open));if(close)closeApp(close.dataset.close);if(pin)togglePin(pin.dataset.pin);if(e.target.id==='add-custom')addCustom()});
root.addEventListener('change',e=>{if(e.target.id==='proxy'){proxyPrefix=e.target.value;saveProxy()}});
async function boot(){root.innerHTML=`<main class="loading"><div class="spinner"></div><h1>Loading desktop assets</h1><p id="progress">Loaded 0 of ${apps.length} app icons</p></main>`;let loaded=0;await Promise.all(apps.map(a=>new Promise(r=>{if(!/^https?:\/\//.test(icon(a))){loaded++;progress.textContent=`Loaded ${loaded} of ${apps.length} app icons`;return r()}const img=new Image();img.onload=img.onerror=()=>{loaded++;progress.textContent=`Loaded ${loaded} of ${apps.length} app icons`;r()};img.src=icon(a)})));render()}
boot();
